# Generated by Django 5.2.5 on 2025-09-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ai_plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
