# Generated by Django 5.2.5 on 2025-09-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_book_ai_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
