# Generated by Django 5.2.5 on 2025-09-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
