# Generated by Django 5.2.5 on 2025-09-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0010_okumagunu'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
