# Generated by Django 5.2.5 on 2025-09-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0011_kitap_cover_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='kitap',
            name='kategoriler',
            field=models.ManyToManyField(blank=True, related_name='kitaplar', to='reading.kategori'),
        ),
    ]
