# Generated by Django 5.2.5 on 2025-09-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0012_kategori_kitap_kategoriler'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
