# Generated by Django 5.2.5 on 2025-09-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0013_kitap_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitap',
            name='status',
            field=models.CharField(choices=[('beklemede', 'Okunacak'), ('okunuyor', 'Şu An Okunuyor'), ('bitti', 'Bitirildi')], default='beklemede', max_length=10),
        ),
    ]
